### ISSUE TITLE
Add missing version to Locale::XGettext::TT2 package

### ISSUE THREAD

**Issue by KohaAloha** [gflohr/Template-Plugin-Gettext#13]
to test...
1/ install pmtools
  
  $ sudo apt install pmtools cpanminus
  $ cpanm  Locale::XGettext::TT2
  $ pmvers Locale::XGettext::TT2
  /usr/bin/pmvers: unknown version for module `Locale::XGettext::TT2'

2/ apply patch
  $ pmvers Locale::XGettext::TT2
  0.7

**Comment by KohaAloha** [comment]
patch attached

**Comment by gflohr** [comment]
The module uses https://metacpan.org/pod/Dist::Zilla::Plugin::PkgVersion and the version is automatically inserted into the released files, see here: https://metacpan.org/release/GUIDO/Template-Plugin-Gettext-0.7/source/lib/Template/Plugin/Gettext.pm.
