### ISSUE TITLE
Allow controlling the UTF-8 flag on translations

### ISSUE THREAD

**Issue by gflohr** [gflohr/Template-Plugin-Gettext#3]
The plug-in currently returns the translation as it is returned by the underlying Locale::Messages and that is with the utf-8 flag turned off.  This is why Locale::Messages::bindtextdomain_filter exists.

There should be a an easy way of controlling that by the user.

The best approach I could think of right now is turning the flag on if the user has set the charset to "utf8" (as opposed to "utf-8"):

     [% USE gtx = Gettext('mydomain', 'fr', 'utf8') %]

Something like this will be in the next version.

**Comment by gflohr** [comment]
Typo in commit message ... still open.

**Comment by ernix** [comment]
@gflohr Isn't that exactly what `Template->new(ENCODING => 'utf8')` does?
http://www.template-toolkit.org/docs/manual/Config.html#section_ENCODING

**Comment by ernix** [comment]
I added a simple test on `t/expand.t` with ENCODING parameter.  But it seems doubling `encode_utf8()` on msgid, but not for `name` param.
https://github.com/ernix/Template-Plugin-Gettext/commit/636ee81b87a23ede9fd33959976b25bd098f9d91

```
✔ kojima:kojiMac Template-Plugin-Gettext[utf8flag]$ prove -Ilib t/expand.t
t/expand.t .. 1/2
    #   Failed test at t/expand.t line 52.
Wide character in print at /Users/kojima/.plenv/versions/5.26.0/lib/perl5/site_perl/5.26.0/Test2/Formatter/TAP.pm line 113.
    #          got: 'ããã«ã¡ã¯ã世界!'
    #     expected: 'こんにちは、世界'
    # Looks like you failed 1 test of 1.

#   Failed test 'utf8_flag'
#   at t/expand.t line 53.
# Looks like you failed 1 test of 2.
t/expand.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests

Test Summary Report
-------------------
t/expand.t (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=1, Tests=2,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.10 cusr  0.01 csys =  0.14 CPU)
Result: FAIL
```

**Comment by gflohr** [comment]
@ernix I don't had`Template->new(ENCODING => 'utf8')` in mind but allowing to explicitely turn the utf8 flag on or off for strings returned by the gettext() functions.  By default, the flag is turned off (see http://search.cpan.org/~guido/libintl-perl-1.29/lib/Locale/libintlFAQ.pod#Can_I_set_the_utf-8_flag_on_strings_returned_by_the_gettext_family_of_functions for an explanation).

I encountered the same problem that your test shows in one project and I had played around with the utf8 flag on the translations, on the template code _and_ the TT2 option `ENCODING => 'utf8'`.  AFAIR, the output was always garbled, as soon as the utf8 flag of the translations was turned on.

I will use your test as a starting point to investigate the problem.

**Comment by gflohr** [comment]
My fix is a little different now: If the string was actually translated (differs from the original) I check whether the utf8 flag was set on the input.  If yes, I also set it, if no, I leave it alone.

@ernix could you pull and check whether your test succeeds now?

And, by the way, I have tested all  combinations of the utf8 flag for the template code, and for the output of gettext() and of the `ENCODING` option of TT2.  My conclusion was that the `ENCODING` option never changed the output at all.  To me it looks like it is completely ignored by TT2.

**Comment by ernix** [comment]
@gflohr 👍 I confirmed, now the garbled text are __fixedup.

https://github.com/ernix/Template-Plugin-Gettext/commit/0e7c63a7a1f11bc00edacdc025a35ec2494195ed
https://github.com/ernix/Template-Plugin-Gettext/commit/d9843695088f2d2d6a06ba9d493848eccafe8a21

```
✔ kojima:skmbp Template-Plugin-Gettext[utf8flag]$ prove -Ilib t/expand.t
t/expand.t .. ok
All tests successful.
Files=1, Tests=2,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.11 cusr  0.02 csys =  0.17 CPU)
Result: PASS
```

**Comment by gflohr** [comment]
Great.  So it looks like the automatic solution fixes this.
