### ISSUE TITLE
xgettext-tt2 doesn't recognize text in statements

### ISSUE THREAD

**Issue by ernix** [gflohr/Template-Plugin-Gettext#5]
Hi, I'm trying to use your module to implement i18n in my website.
Today I encountered some issue while using xgettext-tt2: it doesn't recognize some text in my templates.

### macro_error_msg.tt

```tt2
[%- USE gtx = Gettext('com.example', 'ja') -%]
[%-
  ERR_MSG = {
    foo = gtx.gettext('These texts')
    bar = gtx.gettext('are ignored')
    buz = gtx.gettext('by xgettext-tt2')
  }

  ERR_MSG_FALLBACK = gtx.gettext('unknown')
-%]
[%- MACRO error_msg(key) GET ERR_MSG.exists(key) ? ERR_MSG.item(key) : ERR_MSG_FALLBACK -%]

[%- gtx.gettext('But this one is extracted properly') -%]
```

### command

```
$ xgettext-tt2 --from-code=UTF-8 -o /tmp/test.pot macro_error_msg.tt
```

Is this a problem related to `Locale::XGettext::TT2::Parser` ?
I'm reading a parser portion of your module, but is not obvious at the first glance.

Please correct me if I'm wrong, thanks.

**Comment by gflohr** [comment]
I'm pretty sure that it is a bug in the "parser".  The parser actually uses the regular TT2 parser and just overrides one method in it so that it can intercept the token stream.  I simply didn't think of the possibility that there are multiple invocations of gettext functions in one TT2 expression.

Looks fixable, stay tuned.

**Comment by gflohr** [comment]
I actually cannot reproduce the bug.  All strings get extracted.  I am using exactly your example template and your command-line.

Which version are you using? And can you please look into the source code for version information (because of #7 ...)

**Comment by ernix** [comment]
@gflohr Thank you, it turns out that my `Template::Plugin::Gettext` was way too old.
$ perl -MTemplate::Plugin::Gettext -e 'print "$Template::Plugin::Gettext::VERSION\n";'
0.1

After upgraded `Template::Plugin::Gettext` to v0.4, my problem was solved.

**Comment by gflohr** [comment]
@ernix Okay.  And I have spotted two bugs and fixed them while reproducing your problem.  So, there was a reason for the failure. ;)
